### ISSUE TITLE
tablet loads views instead of views_mobile when views_tablet is not present

### ISSUE THREAD

**Issue by autronix** [neighborland/mobu#1]
Is there any way to load views_mobile as the tablet layout when views_tablet is not present?

At this point, when views_tablet is not present, the templates in views get loaded; the only way around this is to have both views_tablet and views_mobile with the same exact files, which creates redundancy.

I couldn't find any reference on how to achieve this in the docs, any info would be appreciated.

Thanks

**Comment by scottjacobsen** [comment]
I can think of two ways to do this. I haven't tested either, but I don't see why they wouldn't work.

### Use partials

You could put the common view code in partials in `app/views/`, such as `app/views/mobile/foo/_index.html.erb`. Then your `app/views_mobile/foo/index.html.erb` and `app/views_tablet/foo/index.html.erb` could both just be

```
<%= render "mobile/foo/index" %>
```

They would still be duplicate files, but at least they would be one liners.

### Override `tablet_views_path`

You can override `tablet_views_path` in any controller to build the view path you want. See https://github.com/neighborland/mobu/blob/799d0630394d10dbf995ff01a259fd2af8f78eb6/lib/mobu/detect_mobile.rb#L38. Something like 

```
def tablet_views_path
  path = [Rails.root + 'app' + 'views_tablet', Rails.root + 'app' + 'views_mobile'] 
  @@tablet_views_path ||= path
end
```

**Comment by autronix** [comment]
Hello,

Thanks for the tip. I ended up forking the project and managed to get it to work as I needed an urgent solution for a project I was working on.

Thanks a lot for the input!
